apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: tdx-total-keys
spec:
  rules:
  - name: "TDX total keys rule"
    labels:
      "intel.feature.node.kubernetes.io/tdx": "true"
    extendedResources:
      tdx.intel.io/keys: "@cpu.security.tdx.total_keys"
    matchFeatures:
      - feature: cpu.security
        matchExpressions:
          tdx.enabled: {op: Exists}
