---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubelet-kata-cleanup
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kubelet-kata-cleanup
  template:
    metadata:
      labels:
        name: kubelet-kata-cleanup
    spec:
      serviceAccountName: kata-deploy-sa
      hostPID: true
      nodeSelector:
        katacontainers.io/kata-runtime: cleanup
      containers:
        - name: kube-kata-cleanup
          image: quay.io/fidencio/kata-containers:3.7.0-with-ita-v0.0.1
          imagePullPolicy: Always
          command: ["bash", "-c", "/opt/kata-artifacts/scripts/kata-deploy.sh reset"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DEBUG
              value: "false"
            - name: SHIMS
              value: "qemu qemu-tdx"
            - name: DEFAULT_SHIM
              value: ""
            - name: CREATE_RUNTIMECLASSES
              value: "true"
            - name: CREATE_DEFAULT_RUNTIMECLASS
              value: "false"
            - name: ALLOWED_HYPERVISOR_ANNOTATIONS
              value: ""
            - name: SNAPSHOTTER_HANDLER_MAPPING
              value: "qemu-tdx:nydus"
            - name: AGENT_HTTPS_PROXY
              value: ""
            - name: AGENT_NO_PROXY
              value: ""
          securityContext:
            privileged: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
