name: Minor Release
on:
  workflow_dispatch

jobs:
  minor-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the new release version
        run: |
          release_version=$(./tools/packaging/release/release.sh get-release-version)
          echo "RELEASE_VERSION=$release_version" >> "$GITHUB_ENV"

      - name: Update VERSION file
        run: |
          ./tools/packaging/release/release.sh update-version-file

      - name: Create a new release
        run: |
          ./tools/packaging/release/release.sh create-new-release
        env:
          GH_TOKEN: ${{ github.token }}