name: CI | Run stability tests
on:
  workflow_call:
    inputs:
      tarball-suffix:
        required: false
        type: string
      commit-hash:
        required: false
        type: string
      target-branch:
        required: false
        type: string
        default: ""

jobs:
  run-monitor:
    strategy:
      fail-fast: false
      matrix:
        vmm:
          - clh #cloud-hypervisor
          - dragonball
          - qemu
        containerd_version:
          - lts
        snapshotter:
          - overlayfs
          - devmapper
        exclude:
          - snapshotter: devmapper
            vmm: dragonball
    runs-on: garm-ubuntu-2204-smaller
    env:
      CONTAINERD_VERSION: ${{ matrix.containerd_version }}
      KATA_HYPERVISOR: ${{ matrix.vmm }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-hash }}
          fetch-depth: 0

      - name: Rebase atop of the latest target branch
        run: |
          ./tests/git-helper.sh "rebase-atop-of-the-latest-target-branch"
        env:
          TARGET_BRANCH: ${{ inputs.target-branch }}

      - name: Install dependencies
        run: bash tests/functional/stability/gha-run.sh install-dependencies

      - name: get-kata-tarball
        uses: actions/download-artifact@v3
        with:
          name: kata-static-tarball-amd64${{ inputs.tarball-suffix }}
          path: kata-artifacts

      - name: Install kata
        run: bash tests/functional/stability/gha-run.sh install-kata kata-artifacts

      - name: Run kata-monitor tests
        run: bash tests/functional/stability/gha-run.sh run
